export const SHOWMOVIES_POPULAR = 'popular/setMoviePopular'
export const SHOWMOVIES_UPCOMING = 'upcoming/setMovieUpcoming'
export const SHOWMOVIES_NOW_PLAYING = 'now_playing/setMovieNow_playing'
export const SHOWMOVIES_TOP_RATED = 'top_rated/setMovieTop_rated'
export const SHOWERROR = 'error/setError'
export const SHOWLOADING = 'loading/setLoading'
export const SHOWWATCHLIST = 'watchList/setWatchList'